name: CI

on: workflow_dispatch

jobs:
  ci:
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v3

      - name: Mint token
        id: mint
        uses: ./
        with:
          audience: pypi
          request-url: $ACTIONS_ID_TOKEN_REQUEST_URL
          request-token: $ACTIONS_ID_TOKEN_REQUEST_TOKEN

      - name: Check
        run: echo '${{ steps.mint.outputs.api-token }}'
